# QUESTION 1 :- Forest Fire

In [2]:
import pandas as pd 
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn import svm
from sklearn.svm import SVC
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import classification_report
from sklearn.metrics import accuracy_score, confusion_matrix
from sklearn.model_selection import train_test_split, cross_val_score

In [3]:
fire=pd.read_csv('forestfires.csv')
fire

month  day  FFMC    DMC     DC   ISI  temp  RH  wind  rain  ...  monthfeb  \
0     mar  fri  86.2   26.2   94.3   5.1   8.2  51   6.7   0.0  ...         0   
1     oct  tue  90.6   35.4  669.1   6.7  18.0  33   0.9   0.0  ...         0   
2     oct  sat  90.6   43.7  686.9   6.7  14.6  33   1.3   0.0  ...         0   
3     mar  fri  91.7   33.3   77.5   9.0   8.3  97   4.0   0.2  ...         0   
4     mar  sun  89.3   51.3  102.2   9.6  11.4  99   1.8   0.0  ...         0   
..    ...  ...   ...    ...    ...   ...   ...  ..   ...   ...  ...       ...   
512   aug  sun  81.6   56.7  665.6   1.9  27.8  32   2.7   0.0  ...         0   
513   aug  sun  81.6   56.7  665.6   1.9  21.9  71   5.8   0.0  ...         0   
514   aug  sun  81.6   56.7  665.6   1.9  21.2  70   6.7   0.0  ...         0   
515   aug  sat  94.4  146.0  614.7  11.3  25.6  42   4.0   0.0  ...         0   
516   nov  tue  79.5    3.0  106.7   1.1  11.8  31   4.5   0.0  ...         0   

     monthjan  monthjul  monthjun  monthmar  monthmay  monthnov  monthoct  \
0           0         0         0         1         0         0         0   
1           0         0         0         0         0         0         1   
2           0         0         0         0         0         0         1   
3           0         0         0         1         0         0         0   
4           0         0         0         1         0         0         0   
..        ...       ...       ...       ...       ...       ...       ...   
512         0         0         0         0         0         0         0   
513         0         0         0         0         0         0         0   
514         0         0         0         0         0         0         0   
515         0         0         0         0         0         0         0   
516         0         0         0         0         0         1         0   

     monthsep  size_category  
0           0          small  
1           0          small  
2           0          small  
3           0          small  
4           0          small  
..        ...            ...  
512         0          large  
513         0          large  
514         0          large  
515         0          small  
516         0          small  

[517 rows x 31 columns]

In [4]:
data=fire.values

In [5]:
x=data[:,2:-1]
y=data[:,-1]

In [6]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3)

In [7]:
x_train.shape,x_test.shape,y_train.shape,y_test.shape

((361, 28), (156, 28), (361,), (156,))

In [8]:
clf=SVC()
params_grid=[{'kernel':['rbf'],'gamma':[50,25,10,5,1],'C':[10,9,8,7,6,5,4,3,2,1]}]
gsv=GridSearchCV(clf,params_grid,cv=10)
gsv.fit(x_train,y_train)

GridSearchCV(cv=10, estimator=SVC(),
             param_grid=[{'C': [10, 9, 8, 7, 6, 5, 4, 3, 2, 1],
                          'gamma': [50, 25, 10, 5, 1], 'kernel': ['rbf']}])

In [12]:
gsv.best_params_

{'C': 10, 'gamma': 50, 'kernel': 'rbf'}

In [13]:
clf=SVC(C=10,gamma=1)                         # Radial Bias Method
clf.fit(x_train,y_train)
y_pred=clf.predict(x_test)
acc=accuracy_score(y_test,y_pred)
print('Accuracy :',acc)
confusion_matrix(y_test,y_pred)

Accuracy : 0.782051282051282


array([[  2,  34],
       [  0, 120]], dtype=int64)

In [14]:
clf=SVC(kernel='linear',C=10,gamma=1)                         # Linear Method
clf.fit(x_train,y_train)
y_pred=clf.predict(x_test)
acc=accuracy_score(y_test,y_pred)
print('Accuracy :',acc)
confusion_matrix(y_test,y_pred)

Accuracy : 0.9807692307692307


array([[ 34,   2],
       [  1, 119]], dtype=int64)

In [15]:
clf=SVC(kernel='poly',C=10,gamma=1)                         # Poly Method
clf.fit(x_train,y_train)
y_pred=clf.predict(x_test)
acc=accuracy_score(y_test,y_pred)
print('Accuracy :',acc)
confusion_matrix(y_test,y_pred)

Accuracy : 0.9743589743589743


array([[ 35,   1],
       [  3, 117]], dtype=int64)

In [16]:
clf=SVC(kernel='sigmoid',C=10,gamma=1)                         # Sigmoid Method
clf.fit(x_train,y_train)
y_pred=clf.predict(x_test)
acc=accuracy_score(y_test,y_pred)
print('Accuracy :',acc)
confusion_matrix(y_test,y_pred)

Accuracy : 0.7692307692307693


array([[  0,  36],
       [  0, 120]], dtype=int64)

# Question 2 :- Salary Data

In [17]:
salary_train=pd.read_csv('SalaryData_Train(1).csv')
salary_test=pd.read_csv('SalaryData_Test(1).csv')

In [18]:
salary_train

age          workclass    education  educationno        maritalstatus  \
0       39          State-gov    Bachelors           13        Never-married   
1       50   Self-emp-not-inc    Bachelors           13   Married-civ-spouse   
2       38            Private      HS-grad            9             Divorced   
3       53            Private         11th            7   Married-civ-spouse   
4       28            Private    Bachelors           13   Married-civ-spouse   
...    ...                ...          ...          ...                  ...   
30156   27            Private   Assoc-acdm           12   Married-civ-spouse   
30157   40            Private      HS-grad            9   Married-civ-spouse   
30158   58            Private      HS-grad            9              Widowed   
30159   22            Private      HS-grad            9        Never-married   
30160   52       Self-emp-inc      HS-grad            9   Married-civ-spouse   

               occupation    relationship    race      sex  capitalgain  \
0            Adm-clerical   Not-in-family   White     Male         2174   
1         Exec-managerial         Husband   White     Male            0   
2       Handlers-cleaners   Not-in-family   White     Male            0   
3       Handlers-cleaners         Husband   Black     Male            0   
4          Prof-specialty            Wife   Black   Female            0   
...                   ...             ...     ...      ...          ...   
30156        Tech-support            Wife   White   Female            0   
30157   Machine-op-inspct         Husband   White     Male            0   
30158        Adm-clerical       Unmarried   White   Female            0   
30159        Adm-clerical       Own-child   White     Male            0   
30160     Exec-managerial            Wife   White   Female        15024   

       capitalloss  hoursperweek          native  Salary  
0                0            40   United-States   <=50K  
1                0            13   United-States   <=50K  
2                0            40   United-States   <=50K  
3                0            40   United-States   <=50K  
4                0            40            Cuba   <=50K  
...            ...           ...             ...     ...  
30156            0            38   United-States   <=50K  
30157            0            40   United-States    >50K  
30158            0            40   United-States   <=50K  
30159            0            20   United-States   <=50K  
30160            0            40   United-States    >50K  

[30161 rows x 14 columns]

In [19]:
salary_test

age      workclass      education  educationno        maritalstatus  \
0       25        Private           11th            7        Never-married   
1       38        Private        HS-grad            9   Married-civ-spouse   
2       28      Local-gov     Assoc-acdm           12   Married-civ-spouse   
3       44        Private   Some-college           10   Married-civ-spouse   
4       34        Private           10th            6        Never-married   
...    ...            ...            ...          ...                  ...   
15055   33        Private      Bachelors           13        Never-married   
15056   39        Private      Bachelors           13             Divorced   
15057   38        Private      Bachelors           13   Married-civ-spouse   
15058   44        Private      Bachelors           13             Divorced   
15059   35   Self-emp-inc      Bachelors           13   Married-civ-spouse   

               occupation    relationship                 race      sex  \
0       Machine-op-inspct       Own-child                Black     Male   
1         Farming-fishing         Husband                White     Male   
2         Protective-serv         Husband                White     Male   
3       Machine-op-inspct         Husband                Black     Male   
4           Other-service   Not-in-family                White     Male   
...                   ...             ...                  ...      ...   
15055      Prof-specialty       Own-child                White     Male   
15056      Prof-specialty   Not-in-family                White   Female   
15057      Prof-specialty         Husband                White     Male   
15058        Adm-clerical       Own-child   Asian-Pac-Islander     Male   
15059     Exec-managerial         Husband                White     Male   

       capitalgain  capitalloss  hoursperweek          native  Salary  
0                0            0            40   United-States   <=50K  
1                0            0            50   United-States   <=50K  
2                0            0            40   United-States    >50K  
3             7688            0            40   United-States    >50K  
4                0            0            30   United-States   <=50K  
...            ...          ...           ...             ...     ...  
15055            0            0            40   United-States   <=50K  
15056            0            0            36   United-States   <=50K  
15057            0            0            50   United-States   <=50K  
15058         5455            0            40   United-States   <=50K  
15059            0            0            60   United-States    >50K  

[15060 rows x 14 columns]

In [20]:
from sklearn.preprocessing import LabelEncoder
label_encoder=LabelEncoder()
salary_train['workclass']=label_encoder.fit_transform(salary_train['workclass'])
salary_train['education']=label_encoder.fit_transform(salary_train['education'])
salary_train['maritalstatus']=label_encoder.fit_transform(salary_train['maritalstatus'])
salary_train['occupation']=label_encoder.fit_transform(salary_train['occupation'])
salary_train['relationship']=label_encoder.fit_transform(salary_train['relationship'])
salary_train['race']=label_encoder.fit_transform(salary_train['race'])
salary_train['sex']=label_encoder.fit_transform(salary_train['sex'])
salary_train['native']=label_encoder.fit_transform(salary_train['native'])
salary_train

age  workclass  education  educationno  maritalstatus  occupation  \
0       39          5          9           13              4           0   
1       50          4          9           13              2           3   
2       38          2         11            9              0           5   
3       53          2          1            7              2           5   
4       28          2          9           13              2           9   
...    ...        ...        ...          ...            ...         ...   
30156   27          2          7           12              2          12   
30157   40          2         11            9              2           6   
30158   58          2         11            9              6           0   
30159   22          2         11            9              4           0   
30160   52          3         11            9              2           3   

       relationship  race  sex  capitalgain  capitalloss  hoursperweek  \
0                 1     4    1         2174            0            40   
1                 0     4    1            0            0            13   
2                 1     4    1            0            0            40   
3                 0     2    1            0            0            40   
4                 5     2    0            0            0            40   
...             ...   ...  ...          ...          ...           ...   
30156             5     4    0            0            0            38   
30157             0     4    1            0            0            40   
30158             4     4    0            0            0            40   
30159             3     4    1            0            0            20   
30160             5     4    0        15024            0            40   

       native  Salary  
0          37   <=50K  
1          37   <=50K  
2          37   <=50K  
3          37   <=50K  
4           4   <=50K  
...       ...     ...  
30156      37   <=50K  
30157      37    >50K  
30158      37   <=50K  
30159      37   <=50K  
30160      37    >50K  

[30161 rows x 14 columns]

In [21]:
salary_test['workclass']=label_encoder.fit_transform(salary_test['workclass'])
salary_test['education']=label_encoder.fit_transform(salary_test['education'])
salary_test['maritalstatus']=label_encoder.fit_transform(salary_test['maritalstatus'])
salary_test['occupation']=label_encoder.fit_transform(salary_test['occupation'])
salary_test['relationship']=label_encoder.fit_transform(salary_test['relationship'])
salary_test['race']=label_encoder.fit_transform(salary_test['race'])
salary_test['sex']=label_encoder.fit_transform(salary_test['sex'])
salary_test['native']=label_encoder.fit_transform(salary_test['native'])
salary_test

age  workclass  education  educationno  maritalstatus  occupation  \
0       25          2          1            7              4           6   
1       38          2         11            9              2           4   
2       28          1          7           12              2          10   
3       44          2         15           10              2           6   
4       34          2          0            6              4           7   
...    ...        ...        ...          ...            ...         ...   
15055   33          2          9           13              4           9   
15056   39          2          9           13              0           9   
15057   38          2          9           13              2           9   
15058   44          2          9           13              0           0   
15059   35          3          9           13              2           3   

       relationship  race  sex  capitalgain  capitalloss  hoursperweek  \
0                 3     2    1            0            0            40   
1                 0     4    1            0            0            50   
2                 0     4    1            0            0            40   
3                 0     2    1         7688            0            40   
4                 1     4    1            0            0            30   
...             ...   ...  ...          ...          ...           ...   
15055             3     4    1            0            0            40   
15056             1     4    0            0            0            36   
15057             0     4    1            0            0            50   
15058             3     1    1         5455            0            40   
15059             0     4    1            0            0            60   

       native  Salary  
0          37   <=50K  
1          37   <=50K  
2          37    >50K  
3          37    >50K  
4          37   <=50K  
...       ...     ...  
15055      37   <=50K  
15056      37   <=50K  
15057      37   <=50K  
15058      37   <=50K  
15059      37    >50K  

[15060 rows x 14 columns]

In [22]:
x_train_2=salary_train.iloc[:,0:13]
y_train_2=salary_train.iloc[:,13]
x_test_2=salary_test.iloc[:,0:13]
y_test_2=salary_test.iloc[:,13]

In [23]:
def norm_func(i):
    x = (i-i.min())/(i.max()-i.min())
    return (x)

In [24]:
x_train_2 = norm_func(x_train_2)
x_test_2 =  norm_func(x_test_2)

In [31]:
model_linear = SVC(kernel = 'linear',gamma=50,C=10)   # Linear
model_linear.fit(x_train_2,y_train_2)

SVC(C=10, gamma=50, kernel='linear')

In [32]:
y_pred=model_linear.predict(x_test_2)
acc=accuracy_score(y_test_2,y_pred)
confusion_matrix(y_test_2,y_pred)
print('Accuracy:',acc)

Accuracy: 0.8085657370517928


In [33]:
model_rad= SVC(kernel = "rbf",random_state=40,gamma=0.1,C=1.0)      # Radial Bias
model_rad.fit(x_train_2,y_train_2)
y_pred=model_rad.predict(x_test_2)
acc=accuracy_score(y_test_2,y_pred)
confusion_matrix(y_test_2,y_pred)
print('Accuracy:',acc)

Accuracy: 0.8280876494023904


In [28]:
model_poly= SVC(kernel = "poly",random_state=40,gamma=50,C=10)     #Polynomial
model_poly.fit(x_train_2,y_train_2)
y_pred=model_poly.predict(x_test_2)
acc=accuracy_score(y_test_2,y_pred)
confusion_matrix(y_test_2,y_pred)
print('Accuracy:',acc)

Accuracy: 0.8205179282868525


In [35]:
model_sigmoid= SVC(kernel = "sigmoid",random_state=40,gamma=50,C=10)    # Sigmoid
model_sigmoid.fit(x_train_2,y_train_2)
y_pred=model_sigmoid.predict(x_test_2)
acc=accuracy_score(y_test_2,y_pred)
confusion_matrix(y_test_2,y_pred)
print('Accuracy:',acc)

Accuracy: 0.7543160690571049


In [30]:
clf=SVC()
params_grid=[{'kernel':['rbf'],'gamma':[50,25,10,5,1],'C':[10,9,8,7,6,5,4,3,2,1]}]
gsv=GridSearchCV(clf,params_grid,cv=10)
gsv.fit(x_train,y_train)
gsv.best_params_

{'C': 10, 'gamma': 50, 'kernel': 'rbf'}